import styles from "@/styles/Home.module.css";
import Head from "next/head";

import DataView from "./DataView";
import Footer from "./layout/Footer";
import Header from "./layout/Header";

const Home = () => {
  return (
    <>
      <Head>
        <title>Suhaib Ahmad - Estarta Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main} style={{"backgroundColor": "#000000"}}>
        <DataView />
      </main>

      <Footer />
    </>
  );
};

export default Home;
