import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Suhaib Ahmad - Estarta Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Content Placeholder</div>
      </main>
    </>
  );
};

export default Home;
